version: 0.2

env:
  variables:
    ACTION: "deploy" # Default action: 'deploy' or 'destroy'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Switching to a application file..."
      - cd wordpress-app
      - echo "Installing AWS CDK and dependencies..."
      - npm install -g aws-cdk
      - cdk --version
      - echo "Installing project dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Configuring AWS CLI..."
      - aws sts get-caller-identity

  build:
    commands:
      - |
        if [ "$ACTION" == "deploy" ]; then
          echo "Deploying CDK stack..."
          cdk deploy --require-approval never 

        elif [ "$ACTION" == "destroy" ]; then
          echo "Destroying CDK stack..."
          cdk destroy --force

        else
          echo "Invalid ACTION parameter. Use 'apply' or 'destroy'."
          exit 1
        fi

  post_build:
    commands:
      - echo "CDK operation ($ACTION) completed successfully."
